SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

TEXT_PADDING = 20

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 1.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED_BASE = 500
PLAYER_SHOOT_COOLDOWN_BASE = 0.3

SHOT_RADIUS = 5

POWERUP_RADIUS = 10
POWERUP_SPAWN_RATE = 10
POWERUP_KINDS = ("shot_rate", "shot_speed")